---
- name: Configure user
  user:
    name: "{{user}}"
    shell: /bin/zsh
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: Install zsh
  package:
    name: zsh
    state: present

- name: Download oh-my-zsh installer
  get_url:
    url: "{{zsh_url}}"
    dest: "{{user_home}}"
    owner: "{{user}}"
    mode: 0700

- name: Run oh-my-zsh installer
  shell: "{{user_home}}/install.sh"
  args:
    creates: "{{user_home}}/.zshrc"
  ignore_errors: true
  become: true
  become_user: "{{user}}"

- name: Append zshrc 
  blockinfile:
    dest: "{{user_home}}/.zshrc"
    block: |
        alias gs='git status'
        alias gp='git pull'
        alias gd='git diff'
